Use more reliable way to check 'fpm' gem presence
Change-Id: I9074472ba40747be5b7bf055d503564eaada4279
Closes-bug: #1561069

diff --git a/examples/fuel_plugin_example_v2_update/pre_build_hook b/examples/fuel_plugin_example_v2_update/pre_build_hook
--- a/examples/fuel_plugin_example_v2_update/pre_build_hook
+++ b/examples/fuel_plugin_example_v2_update/pre_build_hook
@@ -5,6 +5,10 @@ command -v fpm >/dev/null 2>&1 || {
     echo >&2 "Install 'fpm' to build this plugin. Aborting."; exit 1;
 }
 
+ruby -e "require 'fpm'" 2>&1 || {
+    echo >&2 "'Fpm' binary file is present, but gem seems to be broken! Aborting."; exit 1;
+}
+
 ROOT=$(dirname `readlink -f $0`)
 
 UBUNTU_REPO_PATH=$ROOT/repositories/ubuntu
